// Frontend/src/components/Exit/ExperienceLetter.jsx
import React, { useEffect, useState, useMemo } from "react";
import { apiFetch } from "../../services/hrApi";
import {
  MagnifyingGlassIcon,
  DocumentArrowDownIcon,
  EyeIcon,
  ArrowPathIcon,
  ShieldCheckIcon,
  PrinterIcon,
  XMarkIcon,
  AcademicCapIcon
} from "@heroicons/react/24/outline";
import { SAMPLE_DOCUMENTS, getStatusBadgeClass } from "./exitData";

const LETTER_TYPES = ["All", "Experience Letter", "Relieving Letter", "Service Certificate", "Employment Certificate"];

const ExperienceLetter = ({ user, onViewEmployee }) => {
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [selectedType, setSelectedType] = useState("All");
  const [previewDoc, setPreviewDoc] = useState(null);

  const fetchLetters = async () => {
    try {
      const res = await apiFetch("/api/exit/experience-letters");
      if (res && res.success && res.data && res.data.length > 0) {
        setRecords(res.data);
      } else {
        setRecords(SAMPLE_DOCUMENTS);
      }
    } catch (err) {
      console.warn("Using sample documents:", err);
      setRecords(SAMPLE_DOCUMENTS);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchLetters();
  }, []);

  const filteredRecords = useMemo(() => {
    return records.filter(r => {
      const matchType = selectedType === "All" || r.letterType === selectedType;
      const matchSearch =
        r.employee.toLowerCase().includes(search.toLowerCase()) ||
        r.employeeId.toLowerCase().includes(search.toLowerCase()) ||
        r.department.toLowerCase().includes(search.toLowerCase());
      return matchType && matchSearch;
    });
  }, [records, selectedType, search]);

  const handleRegenerate = (id) => {
    alert("Re-generating certified certificate with updated digital watermark...");
    setRecords(prev => prev.map(r => r.id === id ? { ...r, status: "Issued", issueDate: new Date().toISOString().split("T")[0] } : r));
  };

  return (
    <div className="space-y-6 font-sans">
      {/* Header & Filter Toolbar */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-sm space-y-4">
        <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4">
          <div>
            <h2 className="text-xl font-black text-slate-900 tracking-tight">Exit Documents & Service Certificates</h2>
            <p className="text-xs text-slate-400 mt-0.5">Generate, digitally sign, preview, and issue corporate relieving and experience certificates.</p>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-600 bg-slate-100 px-3 py-1 rounded-full">
              Certificates: {records.length}
            </span>
          </div>
        </div>

        {/* Letter Type Tabs */}
        <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-100">
          {LETTER_TYPES.map((type) => (
            <button
              key={type}
              onClick={() => setSelectedType(type)}
              className={`px-3 py-1.5 text-xs font-bold rounded-lg transition ${
                selectedType === type
                  ? "bg-slate-900 text-white shadow-sm"
                  : "bg-slate-50 text-slate-600 hover:bg-slate-100"
              }`}
            >
              {type}
            </button>
          ))}
        </div>

        {/* Search */}
        <div className="relative pt-1">
          <MagnifyingGlassIcon className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search by employee name, EMP ID, or designation..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-10 pr-4 py-2 text-xs font-semibold focus:outline-indigo-500"
          />
        </div>
      </div>

      {/* Documents Table */}
      <div className="bg-white border border-slate-200/80 rounded-3xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-xs text-slate-700">
            <thead className="bg-slate-50/80 text-[10px] font-black text-slate-400 uppercase tracking-wider border-b border-slate-200">
              <tr>
                <th className="px-5 py-4">Employee</th>
                <th className="px-4 py-4">EMP ID</th>
                <th className="px-4 py-4">Department</th>
                <th className="px-4 py-4">Designation</th>
                <th className="px-4 py-4">Letter Type</th>
                <th className="px-4 py-4">Issue Date</th>
                <th className="px-4 py-4">Generated By</th>
                <th className="px-4 py-4">Approved By</th>
                <th className="px-4 py-4 text-center">Status</th>
                <th className="px-5 py-4 text-center">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-semibold">
              {filteredRecords.map((r) => (
                <tr key={r.id} className="hover:bg-slate-50/70 transition">
                  <td className="px-5 py-4 font-bold text-slate-900">{r.employee}</td>
                  <td className="px-4 py-4 font-mono font-bold text-indigo-600">{r.employeeId}</td>
                  <td className="px-4 py-4 text-slate-600">{r.department}</td>
                  <td className="px-4 py-4 text-slate-600">{r.designation}</td>
                  <td className="px-4 py-4">
                    <span className="font-bold text-slate-900">{r.letterType}</span>
                  </td>
                  <td className="px-4 py-4 text-slate-500">{r.issueDate}</td>
                  <td className="px-4 py-4 text-slate-600">{r.generatedBy}</td>
                  <td className="px-4 py-4 text-slate-600">{r.approvedBy}</td>
                  <td className="px-4 py-4 text-center">
                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-black border uppercase tracking-wider ${getStatusBadgeClass(r.status)}`}>
                      {r.status}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <div className="flex items-center justify-center gap-1.5">
                      <button
                        onClick={() => setPreviewDoc(r)}
                        className="px-2.5 py-1 bg-indigo-50 border border-indigo-200 text-indigo-700 rounded-lg text-xs font-bold hover:bg-indigo-100 transition flex items-center gap-1"
                        title="Preview Certificate"
                      >
                        <EyeIcon className="w-3.5 h-3.5" />
                        <span>Preview</span>
                      </button>

                      <button
                        onClick={() => alert(`Downloading PDF certificate for ${r.employee}...`)}
                        className="p-1.5 text-slate-500 hover:text-indigo-600 rounded-lg border border-slate-200 hover:bg-slate-50"
                        title="Download PDF"
                      >
                        <DocumentArrowDownIcon className="w-4 h-4" />
                      </button>

                      <button
                        onClick={() => handleRegenerate(r.id)}
                        className="p-1.5 text-slate-500 hover:text-slate-800 rounded-lg border border-slate-200 hover:bg-slate-50"
                        title="Regenerate Certificate"
                      >
                        <ArrowPathIcon className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
              {filteredRecords.length === 0 && (
                <tr>
                  <td colSpan={10} className="text-center py-10 text-slate-400">
                    No exit documents found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Corporate Certificate Preview Modal */}
      {previewDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in">
          <div className="bg-white rounded-3xl p-8 shadow-2xl border border-slate-300 w-full max-w-2xl space-y-6 text-slate-800">
            {/* Certificate Header / Letterhead */}
            <div className="border-b-2 border-indigo-900 pb-4 flex justify-between items-start">
              <div>
                <h2 className="text-xl font-black text-indigo-950 tracking-wider">NATION INSURANCE BROKER</h2>
                <p className="text-[10px] text-slate-500 font-semibold uppercase tracking-widest mt-0.5">Corporate Human Resources Department</p>
                <p className="text-[10px] text-slate-400">Ref: {previewDoc.docNumber || "NIB/CERT/2026/891"} · Date: {previewDoc.issueDate || "25 Sep 2026"}</p>
              </div>
              <button
                onClick={() => setPreviewDoc(null)}
                className="text-slate-400 hover:text-slate-700 p-1 rounded-lg hover:bg-slate-100"
              >
                <XMarkIcon className="w-5 h-5" />
              </button>
            </div>

            {/* Certificate Title */}
            <div className="text-center py-2">
              <h3 className="text-base font-black text-slate-900 uppercase tracking-widest underline decoration-indigo-600 underline-offset-8">
                {previewDoc.letterType}
              </h3>
            </div>

            {/* Certificate Body Paragraphs */}
            <div className="space-y-4 text-xs leading-relaxed text-slate-700">
              <p>
                <span className="font-bold">TO WHOMSOEVER IT MAY CONCERN</span>
              </p>
              <p>
                This is to certify that <span className="font-extrabold text-slate-900">{previewDoc.employee}</span> (Employee ID: <span className="font-mono font-bold text-slate-900">{previewDoc.employeeId}</span>) was employed with <span className="font-bold text-slate-900">Nation Insurance Broker</span> as a <span className="font-bold text-slate-900">{previewDoc.designation}</span> in the <span className="font-bold text-slate-900">{previewDoc.department}</span> department from <span className="font-bold">{previewDoc.tenure || "15 Jan 2023 to 20 Sep 2026"}</span>.
              </p>
              <p>
                During their tenure with the organization, they demonstrated exceptional technical competency, professional dedication, and high ethical conduct. All company assets and departmental clearances have been verified and cleared.
              </p>
              <p>
                They are relieved of all duties and responsibilities effective the close of business hours on <span className="font-bold">{previewDoc.issueDate || "20 Sep 2026"}</span>. We thank them for their valuable contributions and wish them every success in their future endeavors.
              </p>
            </div>

            {/* Signatures & Seal */}
            <div className="pt-8 flex justify-between items-end border-t border-slate-200">
              <div>
                <div className="w-28 h-10 border-b border-dashed border-slate-400 flex items-center justify-center text-[10px] text-slate-400 italic">
                  [Digital Signature]
                </div>
                <p className="font-black text-xs text-slate-900 mt-1">{previewDoc.approvedBy || "Anjali Mehta"}</p>
                <p className="text-[10px] text-slate-400">Head – Human Resources</p>
              </div>
              <div className="text-center p-3 rounded-xl border-2 border-dashed border-indigo-200 bg-indigo-50/50">
                <span className="text-[10px] font-black text-indigo-800 block uppercase">Official Corporate Seal</span>
                <span className="text-[9px] text-indigo-600 block">Digitally Verified Document</span>
              </div>
            </div>

            {/* Modal Actions */}
            <div className="flex justify-between items-center pt-2">
              <button
                onClick={() => window.print()}
                className="px-4 py-2 border border-slate-200 text-slate-700 rounded-xl text-xs font-bold hover:bg-slate-50 flex items-center gap-1.5"
              >
                <PrinterIcon className="w-4 h-4" />
                <span>Print Certificate</span>
              </button>
              <div className="flex gap-2">
                <button
                  onClick={() => setPreviewDoc(null)}
                  className="px-4 py-2 border border-slate-200 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-50"
                >
                  Close
                </button>
                <button
                  onClick={() => {
                    alert(`Downloading official signed PDF for ${previewDoc.employee}...`);
                    setPreviewDoc(null);
                  }}
                  className="px-4 py-2 bg-indigo-600 text-white rounded-xl text-xs font-bold hover:bg-indigo-700 shadow-sm flex items-center gap-1.5"
                >
                  <DocumentArrowDownIcon className="w-4 h-4" />
                  <span>Download Signed PDF</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ExperienceLetter;
